project_id = "vbevikjfmrnaiqcaysnx"

[functions.ai-daily-brief]
verify_jwt = false

[functions.ask-rose-outcomes]
verify_jwt = false

[functions.noga-send-counselor-feedback]
verify_jwt = false

[functions.noga-send-new-essay-notification]
verify_jwt = false
