import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';

type Mode = 'feedback' | 'brainstorm' | 'polish' | 'detector';

const SYSTEM: Record<Mode, string> = {
  feedback: `You are an ethical college essay coach. The student will paste a draft and (optionally) the essay prompt.
Return STRICT JSON with this shape:
{
  "thesis_check": string,
  "structure_outline": string[],
  "voice_notes": string,
  "prompt_fit_gaps": string[],
  "socratic_questions": string[]
}
CRITICAL ETHICS: Do NOT rewrite, draft, or produce replacement prose. Do NOT supply sample sentences or paragraphs. Only describe and ask.`,
  brainstorm: `You are an ethical college essay brainstorm coach. Help the student mine experiences and shape an outline.
You may ask follow-up questions and propose themes and outline bullets. You MUST refuse to write essay paragraphs or sample prose.
Reply conversationally in markdown.`,
  polish: `You are a careful copy editor. The student pastes a draft. Identify ONLY surface fixes: typos, run-ons, awkward phrasing, repeated words.
Return STRICT JSON:
{
  "suggestions": [
    { "original": string, "suggested": string, "reason": string }
  ]
}
Do NOT change ideas, voice, structure, or content. Keep suggested edits minimal and within the same sentence.`,
  detector: `You are an AI-text detection heuristic. Analyse the pasted text for likelihood it was generated by a large language model.
Use signals: low perplexity feel, uniform sentence length, generic vocabulary, lack of personal specificity, predictable transitions.
Return STRICT JSON:
{
  "score": number,
  "confidence": "low" | "medium" | "high",
  "summary": string,
  "signals": string[],
  "paragraph_scores": [{ "snippet": string, "score": number }]
}
Score 0 = clearly human, 100 = clearly AI. Always remind: heuristic, not proof.`,
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const { mode, input, prompt, history } = await req.json();
    const m = mode as Mode;
    if (!['feedback', 'brainstorm', 'polish', 'detector'].includes(m)) {
      return new Response(JSON.stringify({ error: 'invalid mode' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const apiKey = Deno.env.get('LOVABLE_API_KEY');
    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'LOVABLE_API_KEY missing' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const messages: any[] = [{ role: 'system', content: SYSTEM[m] }];
    if (m === 'brainstorm' && Array.isArray(history)) {
      for (const h of history) messages.push({ role: h.role, content: h.content });
    } else {
      const userText =
        m === 'feedback'
          ? `Essay prompt:\n${prompt || '(not provided)'}\n\nDraft:\n${input || ''}`
          : input || '';
      messages.push({ role: 'user', content: userText });
    }

    const body: any = {
      model: 'google/gemini-2.5-flash',
      messages,
      stream: true,
    };
    if (m !== 'brainstorm') {
      body.response_format = { type: 'json_object' };
    }

    const resp = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });

    if (!resp.ok) {
      if (resp.status === 429) {
        return new Response(JSON.stringify({ error: 'Rate limited, please try again shortly.' }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (resp.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI credits exhausted. Add credits to your Lovable workspace.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
        );
      }
      const t = await resp.text();
      console.error('AI gateway error:', resp.status, t);
      return new Response(JSON.stringify({ error: 'AI gateway error' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    return new Response(resp.body, {
      headers: { ...corsHeaders, 'Content-Type': 'text/event-stream' },
    });
  } catch (e) {
    console.error(e);
    return new Response(JSON.stringify({ error: (e as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
